<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Hotel_accommodation_System</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Black &amp; Blue Minimalist Modern Initial Font Logo 1.png" />
    <None Remove="confir.png" />
    <None Remove="Confirmation.png" />
    <None Remove="Customer.png" />
    <None Remove="Dasboardrivergreen.png" />
    <None Remove="Dashboard.png" />
    <None Remove="Document.png" />
    <None Remove="Employee.png" />
    <None Remove="Inventory.png" />
    <None Remove="MainwindiowBlack &amp; Blue Minimalist Modern.png" />
    <None Remove="Mainwindiwriverfreen.png" />
    <None Remove="MainwindowBackground.png" />
    <None Remove="Profile.png" />
    <None Remove="Report.png" />
    <None Remove="reportsection.png" />
    <None Remove="Reserve.png" />
    <None Remove="Room.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.1" />
    <PackageReference Include="PDFsharp" Version="6.1.1" />
    <PackageReference Include="PdfSharpCore" Version="1.3.65" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Black &amp; Blue Minimalist Modern Initial Font Logo 1.png" />
    <Resource Include="confir.png" />
    <Resource Include="Confirmation.png" />
    <Resource Include="Customer.png" />
    <Resource Include="Dasboardrivergreen.png" />
    <Resource Include="Dashboard.png" />
    <Resource Include="Document.png" />
    <Resource Include="Employee.png" />
    <Resource Include="Inventory.png" />
    <Resource Include="MainwindiowBlack &amp; Blue Minimalist Modern.png" />
    <Resource Include="Mainwindiwriverfreen.png" />
    <Resource Include="MainwindowBackground.png" />
    <Resource Include="Profile.png" />
    <Resource Include="Report.png" />
    <Resource Include="reportsection.png" />
    <Resource Include="Reserve.png" />
    <Resource Include="Room.png" />
  </ItemGroup>

</Project>
